name: "Ergonomics Guides"
description: "Notes on ergonomics for heavy computer users"
signature: ""
highlighter: rouge
permalink: pretty
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
# enables "edit" link
github:
  # example for a user or organization site
  repo: 'ergonomics-guides/ergonomics-guides.github.io'
  branch: master

  # example for a project site
  # repo: 'edrex/reusable-jekyll-site'
  # branch: gh-pages
prose:
  # needed for prose preview feature
  # siteurl: 'http://GRIZZLYBEAR.github.io'
  # needed for prose "insert page link" feature
  # relativeLinks: 'http://GRIZZLYBEAR.github.io/links.jsonp'
  
  siteurl: 'http://ergonomics-guides.pdxhub.org'
  relativeLinks: 'http://ergonomics-guides.github.io/links.jsonp'
  
  # uncomment to limit editing to the _posts directory
  #rooturl: '_posts'
  media: 'media'
  # metadata:
  #   _posts:
  #     - name: "layout"
  #       field:
  #         element: "hidden"
  #         value: "post"
  #     - name: "tags"
  #       field:
  #         element: "multiselect"
  #         label: "Add Tags"
  #         placeholder: "Choose Tags"
  #         options:
  #           - name: "Honey"
  #             value: "honey"
  #           - name: "Salmon"
  #             value: "salmon"
  #           - name: "Huckleberries"
  #             value: "huckleberries"
  #   _posts/static:
  #     - name: "layout"
  #       field:
  #         element: "hidden"
  #         value: "page"
  #     - name: "permalink"
  #       field:
  #         element: "text"
  #         label: "Permalink"
  #         value: ""
